---
settings:
  name: Astra Control Center 22.08 documentation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: release-notes/whats-new.html
  versions:
  - name: Centro di controllo Astra
    url: "/astra-control-center"
    version-number: '22.08'
  - name: Centro di controllo Astra
    url: "/astra-control-center-2204"
    version-number: '22.04'
  - name: Centro di controllo Astra
    url: "/astra-control-center-2112"
    version-number: '21.12'
  - name: Centro di controllo Astra
    url: "/astra-control-center-2108"
    version-number: '21.08'
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione di Astra Control Center 22.08
    url: "/index.html"
  - section: release-notes
  - section: concepts
  - section: get-started
  - section: use
  - section: rest-api
  - section: support
  - title: Versioni precedenti
    url: "/acc-earlier-versions.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito con Astra Control Center
    links:
    - title: Scopri di più su Astra Control Center
      url: "/concepts/intro.html"
    - title: Novità di Astra Control Center
      url: "/release-notes/whats-new.html"
    - title: Note di rilascio
      url: "/release-notes/rn_overview.html"
    - title: Provalo
      url: "/get-started/setup_overview.html#add-a-license-for-astra-control-center"
    - title: Installare Astra Control Center
      url: "/get-started/install_acc.html"
  - title: Utilizzare Astra Control Center
    links:
    - title: Gestire gli account
      url: "/use/manage-users.html"
    - title: Gestire le applicazioni
      url: "/use/manage-apps.html"
    - title: Proteggi le app
      url: "/use/protect-apps.html"
    - title: Clonare e migrare le applicazioni
      url: "/use/clone-apps.html"
    - title: Replica delle applicazioni su un sistema remoto
      url: "/use/replicate_snapmirror.html"
  - title: Utilizzare l'API di controllo Astra
    links:
    - title: Inizia a utilizzare l'API Astra Control
      url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
    - title: Riferimento API
      url: https://docs.netapp.com/us-en/astra-automation/reference/api_reference.html
    - title: Flussi di lavoro API
      url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
  - title: Utilizzare Astra Control Service
    links:
    - title: Scopri di più su Astra Control Service
      url: https://docs.netapp.com/us-en/astra/get-started/intro.html
    - title: Novità di Astra Control Service
      url: https://docs.netapp.com/us-en/astra/release-notes/whats-new.html
    - title: Avvio rapido per Astra Control Service
      url: https://docs.netapp.com/us-en/astra/get-started/quick-start.html
  - title: Utilizza Astra Data Store
    links:
    - title: Scopri di più su Astra Data Store
      url: https://docs.netapp.com/us-en/astra-data-store/concepts/intro.html
    - title: Novità di Astra Data Store
      url: https://docs.netapp.com/us-en/astra-data-store/release-notes/whats-new.html
    - title: Guida rapida per Astra Data Store
      url: https://docs.netapp.com/us-en/astra-data-store/get-started/quick-start.html
  - title: Descrizioni delle soluzioni
    links:
    - title: PostgreSQL DBaaS con Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
    - title: MySQL DBaaS con Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
    - title: Semplificare la gestione del ciclo di vita di Jenkins
      url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
  - title: Blog e community
    links:
    - title: Discordare il canale
      url: https://discord.gg/NetApp
    - title: Blog di Astra Control
      url: https://cloud.netapp.com/blog/topic/astra
    - title: Community NetApp
      url: https://community.netapp.com/
    - title: Hub Kubernetes
      url: https://cloud.netapp.com/kubernetes-hub
    - title: Dove ottenere aiuto
      url: "/support/get-help.html"
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Tutta la documentazione Astra
