---
sidebar: sidebar 
permalink: concepts/licensing.html 
keywords: license, licensing 
summary: 'Scopri come le azioni che puoi eseguire con Astra Control Center differiscono in base allo stato della licenza e come l"utilizzo di Astra Control Center influisce sul consumo della licenza.' 
---
= Licensing
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Astra Control Center richiede l'installazione di una licenza per abilitare la funzionalità completa di gestione dei dati dell'applicazione. Quando si implementa Astra Control Center senza licenza, viene visualizzato un banner nell'interfaccia utente Web, che avvisa che le funzionalità del sistema sono limitate.

Hai bisogno di una licenza per proteggere le tue applicazioni e i tuoi dati. Fare riferimento a Astra Control Center link:../concepts/intro.html["caratteristiche"] per ulteriori informazioni.

Una volta acquistato il prodotto, si riceveranno un numero di serie e una licenza. È possibile generare il file di licenza NetApp (NLF) da https://mysupport.netapp.com["Sito di supporto NetApp"^].

Puoi anche provare Astra Control Center con una licenza di valutazione, che ti consente di utilizzare Astra Control Center per 90 giorni dalla data di download della licenza. Per ulteriori informazioni, fare riferimento a. link:../get-started/requirements.html["Requisiti"].

Per ulteriori informazioni sulle licenze necessarie per i backend di storage ONTAP, fare riferimento a. link:../get-started/requirements.html["backend di storage supportati"].


NOTE: È possibile aggiungere un cluster, aggiungere un bucket e gestire un backend di storage senza una licenza.



== Come viene calcolato il consumo delle licenze

Quando si aggiunge un nuovo cluster ad Astra Control Center, non viene contato per ottenere licenze consumate fino a quando almeno un'applicazione in esecuzione sul cluster non viene gestita da Astra Control Center.

Quando si inizia a gestire un'applicazione su un cluster, tutte le unità CPU del cluster vengono incluse nel consumo di licenza di Astra Control Center.



== Trova ulteriori informazioni

* link:../use/update-licenses.html["Aggiornare una licenza esistente"]

