---
sidebar: sidebar 
permalink: release-notes/known-issues-ads.html 
keywords: astra, control center, ads, data store, bugs, known issues, problems 
summary: 'I problemi noti identificano i problemi che potrebbero impedire l"utilizzo corretto di questa versione del prodotto.' 
---
= Problemi noti con Astra Data Store e questa release di Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


I problemi noti identificano i problemi che potrebbero impedire l'utilizzo corretto di questa versione del prodotto.

https://docs.netapp.com/us-en/astra-data-store/release-notes/known-issues.html["Consulta questi ulteriori problemi noti di Astra Data Store"^] Ciò potrebbe influire sulla gestione di Astra Data Store con l'attuale release di Astra Control Center.



== I dettagli del volume Astra Data Store non vengono visualizzati nella pagina Storage Backends dell'interfaccia utente di Astra Control Center

Dettagli quali capacità e throughput non vengono visualizzati nell'interfaccia utente. Quando si verifica questo problema, annullare la gestione del back-end dello storage e aggiungerlo nuovamente.



== Per annullare la gestione di un cluster con Astra Data Store è necessario rimuovere prima un'applicazione di sistema gestita

Se hai aggiunto un cluster che contiene Astra Data Store a un cluster Astra Control Center, l'applicazione di sistema astrads viene gestita per impostazione predefinita come applicazione nascosta. Per annullare la gestione del cluster, è necessario prima annullare la gestione dell'applicazione astrads-system. Non è possibile annullare la gestione di questo tipo di applicazione utilizzando l'interfaccia utente di Astra Control Center. Utilizzare invece una richiesta API di Astra Control per rimuovere manualmente l'applicazione:

.Dettagli
[%collapsible]
====
.Fasi
. Ottenere l'ID per il cluster gestito utilizzando questa API:
+
[listing]
----
/accounts/{account_id}/topology/v1/managedClusters
----
+
Risposta:

+
[listing, subs="+quotes"]
----
{
"items": [
{
"type": "application/astra-managedCluster",
"version": "1.1",
*"id": "123ab987-0bc0-00d0-a00a-1234567abd8d",*
"name": "astrads-cluster-1234567",
...
----
. Ottieni l'ID app di sistema astrad gestito:
+
[listing]
----
/accounts/{account_id}/topology/v2/managedClusters/{managedCluster_id}/apps
----
+
Risposta:

+
[listing, subs="+quotes"]
----
{
  "items": [
    [
      *"1b011d11-bb88-40c7-a1a1-ab1234c123d3",*
      "astrads-system",
      "ready"
    ]
  ],
  "metadata": {}
}
----
. Elimina l'app di sistema astrad utilizzando l'ID dell'app acquisito nel passaggio precedente (`1b011d11-bb88-40c7-a1a1-ab1234c123d3`).
+
[listing]
----
/accounts/{account_id}/k8s/v2/apps/{astrads-system_app_id}
----


====


== Trova ulteriori informazioni

* link:../release-notes/known-issues.html["Problemi noti"]
* link:../release-notes/known-limitations.html["Limitazioni note"]

